import pytest
import json
import jwt
from datetime import timedelta, datetime
from flask import current_app


class TestFailTokenAuthentication:
    @pytest.mark.parametrize("amount", [("542"), ("42343"), ("0")])
    def test_missing_token(self, test_client, amount):
        """
        GIVEN get API call
        WHEN user requests CVE
        THEN check if user authenticate with token
        """
        response = test_client.get(f'/cve?amount={amount}')
        assert b"Token is missing" in response.data

    @pytest.mark.parametrize("token", [("ksju453x"), ("324"), ("s s s 2")])
    def test_invalid_token(self, test_client, token):
        """
        GIVEN get API call
        WHEN user provided token header
        THEN check if token is invalid
        """
        headers = {"token": token}
        response = test_client.get(f'/cve', headers=headers)
        assert b"Invalid token." in response.data
        assert response.status_code == 401

    def test_expired_token(self, test_client, user_register):
        data = user_register
        expired_token = jwt.encode(
            payload={'user': data["username"],
                     "exp": datetime.utcnow() - timedelta(seconds=1)},
            key="test_secret_key",
            algorithm="HS256")
        headers = {"token": expired_token}
        response = test_client.get(f'/cve', headers=headers)
        assert response.status_code == 401
        assert b"Token expired." in response.data


class TestFailUserRegister:
    headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json'}

    @pytest.mark.parametrize("password", [("noNumberPassword"), ("a"), ("no spaces"), ("noCapital")])
    def test_invalid_password(self, test_client, password):
        """Check all invalid password cases"""
        data = {
            'username': "ValidUsername11",
            'password': password}

        # dumps - turn python object into a json string
        response = test_client.post(
            '/user/register', data=json.dumps(data), headers=self.headers)
        assert response.status_code == 400

    @pytest.mark.parametrize("username", [("username spaces"), ("a")])
    def test_invalid_username(self, test_client, username):
        """Check all invalid username cases"""
        data = {
            'username': username,
            'password': 'ValidPassword123'
        }
        response = test_client.post(
            '/user/register', data=json.dumps(data), headers=self.headers)
        assert response.status_code == 400

    def test_username_taken(self, test_client):
        data = {
            'username': "Ruby",
            'password': 'ValidPassword123'
        }
        test_client.post('/user/register',
                         data=json.dumps(data), headers=self.headers)
        response = test_client.post(
            '/user/register', data=json.dumps(data), headers=self.headers)
        assert b"User already exists" in response.data
        assert response.status_code == 409


class TestFailUserLogin:
    headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json'}

    def test_invalid_password(self, test_client, user_register):
        data = user_register
        user_register["password"] = "InvalidPassword"
        response = test_client.post(
            '/user/login', data=json.dumps(data), headers=self.headers)
        assert b"User authentication failure" in response.data
        assert response.status_code == 401

    def test_user_not_exists(self, test_client):
        data = {
            'username': "NotExists",
            'password': "DoesNotMatter123"
        }
        response = test_client.post(
            '/user/login', data=json.dumps(data), headers=self.headers)
        assert b"User does not exist" in response.data
        assert response.status_code == 401


class TestFailUserOperations:
    headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json'}

    class TestFailUpdateUser:
        def test_fail_invalid_auth(self, test_client, user_register):
            data = user_register
            data["new_username"] = "NewUpdatedUsername"
            data["password"] = "WrongPassword"
            response = test_client.patch(
                '/user/update', data=json.dumps(data), headers=TestFailUserOperations.headers)
            assert response.status_code == 401
            assert b"Authentication failure" in response.data

        def test_fail_unavailable_username(self, test_client, user_register):
            data = user_register
            data["new_username"] = data["username"]
            response = test_client.patch(
                '/user/update', data=json.dumps(data), headers=TestFailUserOperations.headers)
            assert b"Username unavailable" in response.data
            assert response.status_code == 400

        def test_fail_user_not_exists(self, test_client, user_register):
            data = user_register
            data["username"] = "InvalidUsername"
            data["new_username"] = "ValidNewUsername"
            response = test_client.patch(
                '/user/update', data=json.dumps(data), headers=TestFailUserOperations.headers)
            assert b"Authentication failure." in response.data
            assert response.status_code == 401

    class TestFailUserDelete:
        def test_fail_user_not_exists(self, test_client, user_register):
            data = user_register
            data["username"] = "InvalidUsername"
            response = test_client.delete(
                '/user/delete', data=json.dumps(data), headers=TestFailUserOperations.headers)
            assert response.status_code == 401
            assert b"Authentication failure" in response.data

        def test_fail_invalid_authentication(self, test_client, user_register):
            data = user_register
            data["password"] = "InvalidPassword"
            response = test_client.delete(
                '/user/delete', data=json.dumps(data), headers=TestFailUserOperations.headers)
            assert response.status_code == 401
            assert b"Authentication failure" in response.data


# run for each touple in decorator
@pytest.mark.parametrize("amount", [("2001"), ("893248723487"), ("3478534875")])
def test_too_many_cve_fail(test_client, amount, user_token):
    """
    GIVEN get API call 
    WHEN too many CVEs are requested
    THEN check if the amount of CVEs is right
    """
    token = user_token  # fixture that logs user in and returns token
    headers = {'token': token}
    response = test_client.get(f'/cve?amount={amount}', headers=headers)
    assert b"You've requested too many CVEs at once. Max is 2000." in response.data
